# Generated by Django 4.0.4 on 2022-05-14 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpcode', models.CharField(blank=True, max_length=200, null=True)),
                ('bpname', models.CharField(blank=True, max_length=200, null=True)),
                ('bpcreatedate', models.DateField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VwAgentSKUCustomerClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpcode', models.CharField(max_length=200)),
                ('quarternum', models.IntegerField()),
                ('year', models.IntegerField()),
                ('totalprice', models.DecimalField(decimal_places=0, max_digits=200)),
                ('countofsku', models.IntegerField()),
                ('countofsku500k', models.IntegerField()),
                ('ocrd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.ocrd')),
            ],
        ),
        migrations.CreateModel(
            name='VwAgentPurchaseFrequencyCClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpcode', models.CharField(max_length=200)),
                ('quarternum', models.IntegerField()),
                ('year', models.IntegerField()),
                ('totalprice', models.DecimalField(decimal_places=0, max_digits=200)),
                ('countinvoice', models.IntegerField()),
                ('countinvoice7Mtoup', models.IntegerField()),
                ('countinvoicebetween5to7M', models.IntegerField()),
                ('ocrd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.ocrd')),
            ],
        ),
    ]
