# Generated by Django 4.0.4 on 2022-05-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_vendor_vwagentskucustomerclub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vwagentpurchasefrequencycclub',
            name='countinvoice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vwagentpurchasefrequencycclub',
            name='countinvoice7Mtoup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vwagentpurchasefrequencycclub',
            name='countinvoicebetween5to7M',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vwagentpurchasefrequencycclub',
            name='quarternum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vwagentskucustomerclub',
            name='countofsku',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vwagentskucustomerclub',
            name='countofsku500k',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vwagentskucustomerclub',
            name='quarternum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
